### ISSUE TITLE
9. Функции и этапы процесса обучения

### ISSUE THREAD

**Issue by gdecan** [kleidemos/PsychologyAndPedagogyCredit#10]
В теории обучения выделяется три функции процесса обучения:
1. Образовательная функция состоит в направлении процесса обучения на формирование знаний, умений и навыков (включая их использование), а также опыта творческой деятельности. 
Умение – это владение способом деятельности. К общим умениям и навыкам относятся владение письменной и устной речью, коммуницирование, и прочее. Специальные умения относятся к способам деятельности в отдельных отраслях науки
2. Развивающая функция состоит в развитии личности студента в процессе усвоения знания и способов деятельности. Происходит развитие: логического мышления; различных видов памяти; качеств ума; речи; познавательного интереса и познавательных потребностей.
3. Воспитательная функция заключается в приобщении к культуре, овладении навыками нравственного поведения, формировании мировоззрений.

Процесс обучения может рассматриваться как последовательность циклически повторяющихся этапов (звеньев) изучения и усвоения учебного материала. Этапы процесса обучения:
1) Постановка познавательных целей и задач (проблем), а также подготовка учащихся к восприятию новых знаний. 
2) Организация процесса восприятия новых знаний и способов деятельности (процесса решения учебной проблемы). 
3) Закрепление знаний, формирование умений и навыков путем включения новых знаний в различные виды деятельности. 
4) Использование изученного в новых ситуациях и обобщение знаний.
5) Контроль и оценка результата учебно-познавательной деятельности обучающихся.

**Comment by kleidemos** [comment]
Не знаю, закончил ли ты, но по моему тут перебор воды. Есть большая разница между текстом к одноразовому прочтению и кратким конспектом.

По моему следующий текст является эквивалентом твоего.
*****

В теории обучения выделяется три функции процесса обучения:

1. Образовательная функция - направление процесса обучения на формирование знаний, умений, навыков и опыта творческой деятельности.  
Умение – это владение способом деятельности.  
    * Общие умения: владение письменной и устной речью, коммуницирование, и т.п. 
    * Специальные - способы деятельности в отдельных отраслях науки
2. Развивающая функция - развитии личности студента в процессе усвоения знания (т.е. логическое мышление, память, ум, речь, познавательные способности).
3. Воспитательная функция - приобщение к культуре, социализация.

Процесс обучения может рассматриваться как цикл:
1. Постановка познавательных целей и задач (проблем), а также подготовка к восприятию новых знаний.
2. Восприятие новых знаний и способов деятельности.
3. Закрепление знаний, формирование умений и навыков через их применение.
4. Использование изученного в новых ситуациях и обобщение знаний.
5. Контроль и оценка результата учащихся.

*****
По остальным вопросам та же проблема.

**Comment by gdecan** [comment]
Немного изменил. На деле воды для конспекта не много. К тому же каждому надо будет всё равно исправлять и "добавлять уникальности" конспекту? Проще убрать пару предложений в процессе, чем искать в учебнике и добавлять что-то.

**Comment by kleidemos** [comment]
Видимо придется по быстрому доделать конспекты, а потом заняться сушкой всего и вся. Цели слишком разные.

**Comment by kleidemos** [comment]
Подправил поехавший блок.
