### ISSUE TITLE
13. Методы проблемного обучения

### ISSUE THREAD

**Issue by gdecan** [kleidemos/PsychologyAndPedagogyCredit#12]
Проблемным называют такой вид обучения, в котором изучение и усвоение учащимися новых знаний осуществляется путем систематической постановки и решения учебных проблем. Проблемная ситуация – это психологическое состояние интеллектуального затруднения при решении проблемы, когда человек не может объяснить новый факт и выполнить известное действие знакомыми способами.
Для создания проблемной ситуации необходимы:

- готовность обучаемого к учебной работе, мотивация;
- наличие задания;
- отсутствие у обучаемого знаний о способе выполнения задания;
- наличие у обучаемого знаний, необходимых для восприятия и понимания содержания проблемного задания.

Учебная проблема – это форма проявления логико-психологического противоречия процесса усвоения, определяющее направление умственного поиска, пробуждающее интерес и ведущее к усвоению нового понятия или нового способа действия.
Различают три метода проблемного обучения: 

- Проблемное изложение: преподаватель ставит познавательную задачу с разных сторон, объясняет значимость, затем показывает пути ее решения. Метод демонстрирует путь научного мышления. Непосредственный результат – усвоение способа и логики решения данного типа проблем, но еще без умения самостоятельного решения.
- Частично поисковый (эвристический): преподаватель привлекает студентов для решения учебной проблемы. В результате использования студенты овладевают умением самостоятельно выполнять отдельные шаги решения проблемы и ее исследования, но не обеспечиваются готовностью к решению целостных проблем.
- Исследовательский метод: студенты самостоятельно решают поставленную преподавателем проблему. По мере овладения навыками научного мышления у них есть возможность решать все более и более сложные познавательные задачи. 

//возможно информация ниже – избыточна
Способы создания проблемных ситуаций на занятиях:

- выдвижение главных проблем, отображающих логику и закономерности развития науки в техники;
- столкновение студентов с демонстрациями опыта (эксперимента), требующего теоретического объяснения;
- использование количественных и качественных нестандартных задач;
- постановка практических заданий; построение и анализ графиков, схем и т.д.; конструирование технических компонентов; разработка алгоритмов деятельности различных специалистов; вывод уравнений;
- изучение динамики процессов в статистических схемах, графиках и диаграммах;
- выдвижение реально существующих проблем изучаемой науки;
- проведение учащимися лабораторного эксперимента (в лабораторных условиях);
- постановка заданий на использование логических приемов умозаключения, сравнения, классификации, обобщения, анализа, индукции и т.д.

**Comment by kleidemos** [comment]
Сделай кошерные списки.

**Comment by gdecan** [comment]
Done.
