### ISSUE TITLE
8. Сущность и структура процесса обучения

### ISSUE THREAD

**Issue by MoonL1ght1** [kleidemos/PsychologyAndPedagogyCredit#13]
Обучение представляет собой целостный многоаспектный процесс совместной деятельности преподавателя и студентов, в ходе которой преподаватель нацеливает, информирует, организует и стимулирует деятельность обучаемых, контролирует и оценивает ее, а обучающиеся овладевают знаниями, умениями и навыками. 
Структура процесса обучения состоит из целевого, содержательного, операционно-деятельностного, контрольно-оценочного и результативного компонентов. В реальной педагогической действительности процесс обучения носит циклический характер. Каждый дидактический цикл представляет собой функциональную систему, основанную на совместной деятельности преподавателя и учащихся.
---------дальше можно отсечь-------
В обучении выделяют две составляющие:
- Преподавание – деятельность преподавателя по формированию у учащихся системы знаний и способов деятельности. 
- Учение – учебная деятельность, направленная на приобретение учащимися содержания обучения.

Преподаватель выполняет ряд действий, основными из которых являются: четкое определение целей обучения, планирование содержания и методов обучения, организация учебной деятельности, контроль и коррекция учебной деятельности обучающихся, оценка результатов.
Цели учебно-познавательной деятельности студента делятся на: 
- Внешние - задаются преподавателем;
- Внутренними - сформулированные учащимся самостоятельно или с помощью преподавателя.

Образовательные программы в соответствии с внешними и внутренними целями подразделяются на общие для всех и индивидуальные для каждого студента.
Информационная и внешняя образовательная среда определяет условия для реализации процесса обучения. Самоопределение обучающихся и принятие ими решений в процессе образовательной деятельности происходит непрерывно.
Результатом учебно-познавательной деятельности являются знания, умения и навыки учащегося.
В процессе решения учебно-познавательных задач осуществляются закрепление и усвоение знаний, их применение для изучения нового материала, формирование умений и навыков.

**Comment by kleidemos** [comment]
Выдели блоки типа: В множестве А есть типы Б и В. Б есть ... . В есть ... .

**Comment by MoonL1ght1** [comment]
обновил
