### ISSUE TITLE
10. Структура и виды учебной деятельности

### ISSUE THREAD

**Issue by MoonL1ght1** [kleidemos/PsychologyAndPedagogyCredit#14]
Структура учебно-познавательной деятельности содержит следующие структурные компоненты: предмет, цель, мотивы, средства, учебные действия и способы их выполнения, продукт (результат). Учебно-познавательную деятельность можно рассматривать как деятельность по решению учебных задач.
------отсекай от сюда-------
В деятельности по решению учебных задач могут быть выделены следующие взаимосвязанные компоненты: 
- анализ и понимание задачи; 
- «принятие» учебной задачи; 
- актуализация имеющихся знаний, необходимых для ее решения; 
- составление плана решения задачи; 
- практическое ее осуществление; 
- контроль (самоконтроль) и оценка решения задачи; 
----до сюда------

По уровню мышления выделяются два вида учебно-познавательной деятельности: репродуктивная и продуктивная (творческая).
Репродуктивная деятельность – это действия по образцу, например повторение пройденного материала и его объяснение, решение типовых задач по известному алгоритму, подготовка и чтение доклада на основе самостоятельной работы с литературой и др. 
Творческая деятельность – решение нестандартных задач, проведение лабораторного эксперимента, учебно-исследовательская работа, конструирование технических изделий и т.д.

**Comment by kleidemos** [comment]
Тут пару списков напрашиваются. Тот что в отсекаемом блоке раздели по ;.
И лучше стандартизировать "определения" репродуктивной и продуктивной деятельности.

**Comment by MoonL1ght1** [comment]
обновил

**Comment by kleidemos** [comment]
@MoonL1ght1 Ты хоть смотри как делишь, я же не зря написал про ;.
Исправил ручками. Пошел вливать.
