### ISSUE TITLE
29. Личностные свойства преподавателя

### ISSUE THREAD

**Issue by MoonL1ght1** [kleidemos/PsychologyAndPedagogyCredit#15]
Педагогическая профессия относится к типу «Человек – человек» и определяется следующими качествами человека: устойчиво хорошим самочувствием в ходе работы с людьми, потребностью в общении, способностью мысленно ставить себя на место другого человека, быстро понимать намерения, настроения других людей, быстро разбираться во взаимоотношениях людей, хорошо помнить и держать в уме знания о личных качествах многих и разных людей. Человеку этой профессиональной схемы свойственны: умение руководить, учить и воспитывать людей, умение слушать и выслушивать; широкий кругозор; речевая культура; наблюдательность к проявлениям чувств, ума и характера человека, к его поведению; способность мысленно представлять его внутренний мир; «проектировочный подход к человеку, основанный на уверенности, что человек всегда может стать лучше»; способность к сопереживанию; наблюдательность.
Главными требованиями, предъявляемыми к преподавателю, являются: любовь к учащимся, к педагогической деятельности, наличие специальных знаний в той области, по которой он преподает, педагогической интуиция, высоко развитый интеллект, высокий уровень общей культуры и нравственности, профессиональное владение разнообразными методами обучения и воспитания студентов. Все эти свойства не являются врожденными. Они приобретаются систематическим и упорным трудом, огромной работой преподавателя
над собой.
Перечень свойств преподавателя, по мнению преподавателей:
• профессионализм и глубокое знание своего предмета;
• умение образно и доступно излагать свои мысли;
• высокая общая культура и эрудиция;
• быстрота реакции и мышления;
• умение отстаивать и защищать свою точку зрения;
• умение пользоваться невербальными средствами;
• способность понимать психологию студента, его достоинства и недостатки;
• внимательность по отношению к людям, доброжелательность и терпеливость;
• строгость в сочетании со справедливостью;
• психологическая устойчивость и находчивость в трудных ситуациях;
• аккуратный внешний вид.
Качества, которые противопоказаны преподавателю:
• высокомерие, грубость, недоброжелательность;
• самовлюбленность;
• менторство;
• застенчивость;
• медленная реакция и консерватизм;
• стремление подавить студента;
• несобранность и лень;
• излишняя эмоциональность, неуравновешенность;
• отсутствие педагогического мастерства.
А.К. Маркова и Л.М. Митина выделяют следующие психологические качества преподавателя, важные для его педагогической деятельности.
• Педагогическая эрудиция
• Практическое педагогическое мышление
• Педагогическая интуиция
• Педагогическая наблюдательность
• Педагогическое предвидение
• Педагогическая рефлексия

**Comment by MoonL1ght1** [comment]
необходимо урезать, хз как

**Comment by kleidemos** [comment]
Пока так сократил.

*****
Профессия педагога относится к типу "Человек - человек" и требует от человека:
* хороших социальных навыков;
* психологическую устойчивость при работе с людьми;
* учет личных качеств разных людей;
* и высокую эмпатию.

Человеку этой профессиональной схемы свойственны: 
* умение руководить и выслушивать, учить и воспитывать людей, 
* хорошие речь и кругозор;
* наблюдательность (особенно к поведению людей); 
* эмпатия; 
* гуманистический проектный подход к человеку; .

Требования к преподавателю: 
* любовь к учащимся, к педагогической деятельности, 
* знание предметной области, 
* педагогическая интуиция, 
* интеллект и интеллигентность,
* владение методами обучения и воспитания. 

> Все эти свойства не являются врожденными. Они приобретаются систематическим и упорным трудом, огромной работой преподавателя над собой.

Перечень свойств преподавателя, по мнению преподавателей:
* знание предметной области;
* знание риторики;
* быстрота реакции и мышления;
* умение пользоваться невербальными средствами;
* высокая общая культура и эрудиция;
* способность учитывать личные качества студента;
* _внимательность и доброжелательность в отношении к людям;_
* строгость и справедливость;
* психологическая устойчивость;
* опрятность.

Качества, которые противопоказаны преподавателю:
* любые проявления слабости, _// будь то лень, застенчивость, самовлюбленность или неуравновешенность_;
* менторство;
* медленная реакция и консерватизм;
* отсутствие педагогического мастерства.

**Comment by kleidemos** [comment]
@MoonL1ght1 Вот зачем ты удалил комментарий? Теперь хрен пойми почему needhelp,
