### ISSUE TITLE
18. Практические занятия (семинар, практикум и лабораторная работа)

### ISSUE THREAD

**Issue by Kazantsev-Aleksandr** [kleidemos/PsychologyAndPedagogyCredit#21]
_**Семинар**_ - углубленного изучения дисциплины

Структура семинарских занятий :

- Постановка темы (проекта) и целей семинара
- Чтение  докладов  учащимися
- Дискуссия
- Подведение итогов, оценка
- Выдача задания на дом

Суть семинарских занятий:

1. Cоздать непринужденную обстановку, организовать оживленную дискуссию 
2. Развить активность обучающихся
3. Добиться свободного выступления студентов, способности к логическому анализу и оценке своих выступлений

Недостатки : 
1. нет тесного сотрудничества, общения с выступающими
2. интеллектуальная пассивность (один читает, остальные слушают)
3. отсутствует возможность формировать навыки профессионального общения и взаимодействия
4. студенты  имеют  возможность  заниматься  во  время  семинара другой работой.

Рекомендуется использовать активные методы обучения:

- С элементами проблемности - наличие проблемы и стремление найти её решение.
- Метод беседы ("сократовский") - вопрос-ответ
- Мозговой штурм - генерация идей, активация творческого мышления
- Анализ конкретной ситуации - решение студентами кейса из профессиональной деятельности

_**Практическое занятие**_ - решение прикладных задач,изученных на  лекциях.

Задачи: 

1. Закрепить , углубить теоретические знания
2. Изучить решение практических задач и других видов заданий
3. Обучение работы с книгами, документацией, схемами и тд.
4. Выработка навыком самостоятельной работы

Занимают большую часть времени, дополняют лекции. Рекомендуется варьировать сложность задач от легких к сложным.

_**Лабораторные занятия**_ - углубление и закрепление теоретических знаний путем  проведения  экспериментов.

Цели: 

1. углубление  и  закрепление  знаний
2. приобретение навыков , требуемых при проведении научных экспериментов
3. формирование навыков организации, планирования и проведения экспериментального исследования.

**Основное требование** к лабораторному практикуму – выбор содержания учебного материала и  формы организации занятия, способствующих развитию творческих способностей и самостоятельности в решении научных и практических задач.

Виды организации лабораторных работ:  // не обязательно

- Фронтальные - одновременное выполнение работы всеми студентами
- По циклам - разделение по темам лекций
- Индивидуальный - дает возможность распределения и чередования тем студентами
- Смешанный (чаще всего используется)

_Коллоквиум_ -  собеседование  преподавателя  со  студентами  по  поводу предстоящей лабораторной работы.
 Цель - проверка усвоения теоретического материала, понимание сущности явлений и процессов, происходящих в лабораторном эксперименте; проверка знания приборов и аппаратуры; порядка проведения и тд.

**Comment by kleidemos** [comment]
Это рекорд.

**Comment by Kazantsev-Aleksandr** [comment]
Возможно многовато получилось. Могу сжать , преобразовав некоторые списки в обычное перечисление

**Comment by kleidemos** [comment]
Ну как выяснилось можно и больше сделать. Чисто из-за времени волью. утешает, что здесь в основном списки.
