### ISSUE TITLE
19. Планирование и организация самостоятельной работы студентов

### ISSUE THREAD

**Issue by Kazantsev-Aleksandr** [kleidemos/PsychologyAndPedagogyCredit#22]
Элементы управления (самоуправления) самостоятельной работы студента: 

- Целеполагание
- Планирование и орг-я работы
- Контроль
- Устранение ошибок

4 функции :

1. Мотивация
2. Планирование
3. Организация
4. Контроль и оценка

Исходные данные для планирования – учебный план.

Условия для успешного выполнения самостоятельной работы:

1. мотивированность учебного задания;
2. четкая постановка познавательных задач;
3. алгоритм, метод выполнения работы, знание студентами способов ее выполнения;
4. четкое определение преподавателем форм отчетности, объема работы, сроков ее представления;
5. определение видов и времени консультационной помощи;
6. виды и формы контроля;
7. критерии оценки, отчетности и т.д.

Обязательная сам. работа – К текущим занятиям 
Контролируемая – Индивидуальные задания

**Comment by Kazantsev-Aleksandr** [comment]
Элементы управления (самоуправления) самостоятельной работы студента: 
•	Целеполагание
•	Планирование и орг-я работы
•	Контроль
•	Устранение ошибок
4 функции :
1.	Мотивация
2.	Планирование
3.	Организация
4.	Контроль и оценка
Исходные данные для планирования – учебный план.
Условия для успешного выполнения самостоятельной работы:
1) мотивированность учебного задания;
2) четкая постановка познавательных задач;
3) алгоритм, метод выполнения работы, знание студентами способов ее выполнения;
4) четкое определение преподавателем форм отчетности, объема работы, сроков ее представления;
5) определение видов и времени консультационной помощи;
6) виды и формы контроля;
7) критерии оценки, отчетности и т.д.
Обязательная сам. работа – К текущим занятиям 
Контролируемая – Индивидуальные задания

**Comment by kleidemos** [comment]
Верстка поехала. Списки не по канону.
