### ISSUE TITLE
20. Технология модульного обучения

### ISSUE THREAD

**Issue by Kazantsev-Aleksandr** [kleidemos/PsychologyAndPedagogyCredit#23]
**Модуль** -  автономная организационно-методическая структура учебной дисциплины, которая включает в себя дидактические цели, логически завершенную единицу учебного материала, методическое руководство.

**Цель** – создание благоприятных условий развития путем обеспечения гибкости содержания обучения, приспособления дидактической системы к индивидуальным потребностям личности и уровню базовой подготовки.

Содержание каждого модуля должно составлять следующие структурные элементы:

- дидактические цели, трансформирующиеся в целевую программу действий для обучающихся
- Учебный материал
- Методическое обеспечение
- Информацию о способах освоения учебного модуля и медотах контроля и самоконтроля результата учебн. деятельности студента.

**Цель разработки модулей** – расчленение содержания курса на компоненты в соответствии с задачами, определение видом и форм обучения и согласование их во времени.

Каждый студент переходит от модуля к модулю по мере усвоения материала и проходит этапы текущего контроля (тестирования).

Принципы: 

1. Модульности -  использование  в  процессе обучения модулей как основного средства усвоения обучающимися дозы учебной информации.
2. Структурированного содержания – деление учебного материала в рамках модуля на структурные элементы, перед каждым из которых ставится дидактическая цель.
3. Действенности и оперативности знаний и их системы -  обучения не только видам деятельности,  но  и  способам  действий.
4. Гибкости – построение программы с обеспечением возможности приспособления содержания обучения к индивидуальным возможностям и потребностям обучаемых.
5. Сотрудничества - сотрудничество между преподавателем (консультанта-координатора), и обучающимися.
6. Реализации обратной связи - управление учебным процессом путем создания системы контроля и самоконтроля.

**Comment by Kazantsev-Aleksandr** [comment]
Модуль -  автономная организационно-методическая структура учебной дисциплины, которая включает в себя дидактические цели, логически завершенную единицу учебного материала, методическое руководство (в том числе дидактические материалы и систему контроля).
Цель – создание благоприятных условий развития путем обеспечения гибкости содержания обучения, приспособления дидактической системы к индивидуальным потребностям личности и уровню базовой подготовки.
Содержание каждого модуля должны составлять следующие структурные элементы:
•	дидактические цели, трансформирующиеся в целевую программу действий для обучающихся;
•	Учебный материал
•	Методическое обеспечение
•	Информацию о способах освоения учебного модуля и медотах контроля и самоконтроля результата учебн. деятельности студента
Цель разработки модулей – расчленение содержания курса на компоненты в соответствии с задачами, определение видом и форм обучения и согласование их во времени.
Каждый студент переходит от модуля к модулю по мере усвоения материала и проходит этапы текущего контроля (тестирования).
Принцип модульности -  использование  в  процессе обучения модулей как основного средства усвоения обучающимися дозы учебной информации.
Принцип структурированного содержания – деление учебного материала в рамках модуля на структурные элементы, перед каждым из которых ставится дидактическая цель. 
Принцип действенности и оперативности знаний и их системы -  обучения не только видам деятельности,  но  и  способам  действий.
Принцип гибкости – построение программы с обеспечением возможности приспособления содержания обучения к индивидуальным возможностям и потребностям обучаемых.
Принцип сотрудничества - сотрудничество между преподавателем (консультанта-координатора), и обучающимися.
Принцип реализации обратной связи - управление учебным процессом путем создания системы контроля и самоконтроля.

**Comment by kleidemos** [comment]
1. Некошерный список.
2. Сформируй список из принципов. 
3. bold на названия.

**Comment by kleidemos** [comment]
Подправил список.
@Kazantsev-Aleksandr В содержание модуля косит склонение и регистр. Возможно что-то потерял.
