### ISSUE TITLE
21. Информационно-компьютерная технология обучения

### ISSUE THREAD

**Issue by Kazantsev-Aleksandr** [kleidemos/PsychologyAndPedagogyCredit#24]
Имеет ряд особенностей : Оперативная передача информации на любые расстояния, эл. литература, индивидуализация обучения,  доступ к различным источникам информации и тд)

Позволяет использовать электронные издания учебников обучающие программы и системы, виртуальные лабораторий и тд. (“Компьютерные обучающие системы” - программные средства учебного назначения).

Особенность дист. обучения – усвоение знаний путем самостоятельной работы с различными источниками, а не традиционными методами(лекции, семинары и тд).

Преимущества :

- Возможность совместной деятельности
- Дист. контроль знаний
- Увеличение числа “студентов” 
- Доступ к мировым образовательным ресурсам
- Публикация работ в Интернете

Недостаток – проблема защиты авторских прав.

Модель обучения методике дистанционного обучения включает 3 этапа :

1. Формирование первоначальных знаний, умений  и  навыков,  необходимые  для  обучения.
2. Формирование основных знаний, умений и навыков,
3. Формирование навыков  самостоятельной  работы

**Comment by Kazantsev-Aleksandr** [comment]
Имеет ряд особенностей : Оперативная передача информации на любые расстояния, эл. литература, индивидуализация обучения,  доступ к различным источникам информации и тд)

Позволяет использовать электронные издания учебников обучающие программы и системы, виртуальные лабораторий и тд. (“Компьютерные обучающие системы” - программные средства учебного назначения).
Особенность дист. обучения – усвоение знаний путем самостоятельной работы с различными источниками, а не традиционными методами(лекции, семинары и тд).
Преимущества :
•	Возможность совместной деятельности
•	Дист. контроль знаний
•	Увеличение числа “студентов” 
•	Доступ к мировым образовательным ресурсам
•	Публикация работ в Интернете
Недостаток – проблема защиты авторских прав.
Модель обучения методике дистанционного обучения включает 3 этапа :
1.	Формирование первоначальных знаний, умений  и  навыков,  необходимые  для  обучения.
2.	Формирование основных знаний, умений и навыков,
3.	Формирование навыков  самостоятельной  работы

**Comment by kleidemos** [comment]
Некошерный список.
