### ISSUE TITLE
15. Метод проектов

### ISSUE THREAD

**Issue by Vingez** [kleidemos/PsychologyAndPedagogyCredit#25]
Методом проектов называют совокупность приемов и познавательных действий студентов по овладении определенной системой знаний, умений, навыков путем самостоятельной проектной деятельности, направленной на решение практической задачи. Метод предполагает рациональное сочетание теоретических знаний из различных областей науки и их практического применения для решения конкретных проблем в совместной деятельности студентов.

Для эффективного применения метода проектов необходимо соблюдать следующие требования: 
1. Наличие значимой в творческом плане проблемы, требующей интегрированного знания, исследовательского поиска для ее решения 
2. Практическая, теоретическая или познавательная значимость предполагаемых результатов. 
3. Самостоятельная деятельность учащихся. 
4. Структурирование содержательной части проекта.
5. Использование исследовательских методов.

Результаты выполненных проектов должны быть «осязаемыми», т.е. если это теоретическая проблема, то конкретное ее решение, если практическая – конкретный результат, готовый к внедрению.

В настоящее время принято выделять семь основных этапов работы над проектом: 

- организационный; 
- выбор и обсуждение главной идеи, целей и задач будущего проекта; 
- обсуждение методических аспектов и организация работы студентов; 
- структурирование проекта с выделением подзадач для определенных групп учащихся, подбор необходимых материалов;
- работа над проектом; 
- подведение итогов, оформление результатов; 
- презентация проекта.

**Comment by kleidemos** [comment]
Нижний список некошерный.

**Comment by Vingez** [comment]
Исправил список
