### ISSUE TITLE
14. Эвристические (групповые) методы решения проблем

### ISSUE THREAD

**Issue by Vingez** [kleidemos/PsychologyAndPedagogyCredit#26]
В групповой учебно-познавательной деятельности каждый студент активно участвует в решении поставленной проблемы, взаимодействует с другими субъектами деятельности, реализуя свой интеллектуальный потенциал. Хорошо организованная и сплоченная группа более продуктивна, чем то же число людей, работающих в одиночку
**Метод «мозгового штурма»** состоит из следующих этапов:
1. Формулирование проблемы, которую необходимо решить; 
2. Тренировочная сессия-разминка. Упражнения в быстром поиске ответов на вопросы и задачи тренировочной сессии. 
3. «Мозговой штурм» поставленной проблемы. Генерирование идей в рабочих группах. 
4. Оценка и отбор наилучших идей. 

**Анализ конкретной ситуации (ситуационный метод):**
Учебная группа делится на несколько подгрупп, каждая из них получает описание конкретных ситуаций. Преподаватель определяет круг задач для подгрупп. Групповая работа над ситуацией заключается в ее анализе, выявлении проблемы, поиске путей ее решения, обсуждении вариантов решения. Затем эти варианты выносятся на общую дискуссию. В результате вырабатывается коллективное суждение о ситуации или решение проблемы. 

**Групповая дискуссия**
Тема дискуссии  формулируется. На занятии начинается свободная дискуссия. Каждый участник дискуссии за отведенное время высказывает свою точку зрения относительно обсуждаемых вопросов. В конце дискуссии преподаватель подводит итоги, обобщает выдвинутые предложения.

**Метод эвристических вопросов.**
Строиться на ответах на типичные эвристические вопросы, состоит из этапов:

- понижение проблемности до оптимального уровня 
- дроблении информации 
- целеполагании (каждый новый эвристический вопрос формирует новую стратегию – цель деятельности).

**Comment by kleidemos** [comment]
Нижний список некошерный.

**Comment by Vingez** [comment]
Исправил список
