### ISSUE TITLE
16. Система организационных форм обучения

### ISSUE THREAD

**Issue by Vingez** [kleidemos/PsychologyAndPedagogyCredit#28]
Организационные формы обучения являются способами осуществления взаимодействия учащихся и преподавателей, в рамках которых реализуются содержание и методы обучения. 

В педагогической теории и практике различают следующие формы организации: 

- лекции
- семинарские занятия 
- практические занятия
- лабораторные работы 
- самостоятельная учебная работа

Кроме того, в вузах организуются:

- коллоквиумы
- курсовые работы
- производственная практика 
- научно-исследовательская работа студентов 
- студенческие конференции
- дипломное проектирование

Каждый вид занятия занимает определенное место в образовательном процессе и выполняет конкретные функции. Учебно- познавательная деятельность строится по следующей схеме: 

- постановка целей и задач, мотивация познавательной активности (на каждом занятии); 
- организация изучения теоретического материала (первичное восприятие), формирование ориентированной основы деятельности (лекции); 
- закрепление знаний (запоминание), формирование умений и навыков (лабораторные работы, семинарские занятия, самостоятельная работа); 
- применение знаний, умений и навыков (лабораторные работы, семинарские занятия, практикум); 
- обобщение и контроль знаний, умений и навыков

**Comment by kleidemos** [comment]
Формы организации стоит выделить в список.

**Comment by Vingez** [comment]
Выделил в список
