### ISSUE TITLE
11. Принципы обучения

### ISSUE THREAD

**Issue by gdecan** [kleidemos/PsychologyAndPedagogyCredit#29]
Принципы обучения – это исходные нормативные требования к организации и осуществлению образовательного процесса, определяющие характер взаимоотношений преподавателя и учащихся.
Общепризнанными являются: научность, наглядность, доступность обучения, активность учащихся, систематичность и последовательность обучения, прочность усвоения знаний, связь теории с практикой, рациональное сочетание индивидуальной и коллективной форм учебной деятельности.

- _Принцип научности обучения_: для усвоения студентам необходимы подлинные, объективные и прочно установленные наукой знания и при этом использовались подходы обучения, по характеру приближающиеся к методам изучаемой науки.
- _Принцип наглядности (единства конкретного и абстрактного)_: эффективность обучения зависит от целесообразного привлечения органов чувств к восприятию учебного материала, т.е. применения наглядности – схем, макетов и т.д. 
- _Принцип доступности обучения_: содержание, объем изучаемого материала, методы его изучения соответствовали уровню умственного развития учащихся и их возможностям.
- _Принцип сознательности и активности_: процесс обучения становится более эффективным при активной учебно-познавательной деятельности.
- _Принцип систематичности и последовательности обучения_: преподавание и учение должно быть в определенном порядке, в системе. 
- _Принцип прочности усвоения_: знания, умения и навыки должны прочно закрепляться в сознании и действиях обучаемых.
- _Принцип связи теории с практикой_: необходимо, чтобы студенты от эмпирических наблюдений шли к теоретическим обобщениям и от них – к практике (либо шли наоборот). Важно, чтобы система учебных задач и других заданий по теме обеспечивали сочетание теории и практики.
- _Принцип рационального сочетания индивидуальной и коллективной форм учебной деятельности_: преподаватель может и должен использовать самые разнообразные формы организации обучения, на которых целесообразно организовывать различные способы взаимодействия учащихся.

**Comment by kleidemos** [comment]
Названия принципов стоило бы выделить.

**Comment by gdecan** [comment]
Выделил курсивом.
