### ISSUE TITLE
4. Федеральный государственный образовательный стандарт (по специальности)

### ISSUE THREAD

**Issue by AlmazAltynguzin** [kleidemos/PsychologyAndPedagogyCredit#31]
Федеральный государственный образовательный стандарт - это система основных параметров, принимаемых в качестве государственной нормы образованности, отражающей общественный идеал и учитывающей возможность реальной личности и системы образования по достижению этого идеала. Для каждого уровня образования разрабатывается соответствующий стандарт. Стандарты профессионального образования на каждом уровне разделяются по специальностям.

ФГОС высшего профессионального образования устанавливает: 
- структуру содержания образования;
- общие требования к подготовке специалистов (цели образования);
- общие нормативы учебной нагрузки студентов и ее объем;
- академические свободы вуза в определении содержания образования;
- порядок разработки и утверждения государственных требований к содержанию и уровню подготовки выпускников по конкретным специальностям;
- правила госконтроля за соблюдением требований к качеству подготовки специалистов.

По закону РФ “Об образовании” государственными органами власти нормируется лишь минимальный необходимый уровень образованности, а содержания образования сверх этой нормы находятся в компетенции регионов и самих образовательных учреждений. В следствии этого, в государственном стандарте высшего профессионального образования выделяют три уровня:  федеральный, национально-региональный и вузовский. 
Федеральный уровень содержания образования определяет те нормативы, соблюдение которых обеспечивает единство высшего образования в России, а также интеграцию личности выпускника в систему мировой экономики и культуры. 
Национально-региональный уровень содержит нормативы в области родного языка и литературы, вопросы истории, искусства, региональной экономики и др. Они относятся к компетенции региональных органов управления образованием. 
Вузовский уровень содержания образования определяется самим образовательным учреждением. Но в стандарте указан объем содержания образования (в часах), отражающего специфику и направленность отдельного образовательного учреждения .

**Comment by kleidemos** [comment]
Поставь официальное название, ты создаешь приключение парсеру. _// хотя я все равно сделал ориентацию по id_

**Comment by AlmazAltynguzin** [comment]
Федеральный государственный образовательный стандарт - это система основных параметров, принимаемых в качестве государственной нормы образованности, отражающей общественный идеал и учитывающей возможность реальной личности и системы образования по достижению этого идеала. Для каждого уровня образования разрабатывается соответствующий стандарт. Стандарты профессионального образования на каждом уровне разделяются по специальностям.
ФГОС высшего профессионального образования устанавливает: 
- структуру содержания образования;
- общие требования к подготовке специалистов (цели образования);
- общие нормативы учебной нагрузки студентов и ее объем;
- академические свободы вуза в определении содержания образования;
- порядок разработки и утверждения государственных требований к содержанию и уровню подготовки выпускников по конкретным специальностям;
- правила госконтроля за соблюдением требований к качеству подготовки специалистов.
По закону РФ “Об образовании” государственными органами власти нормируется лишь минимальный необходимый уровень образованности, а содержания образования сверх этой нормы находятся в компетенции регионов и самих образовательных учреждений. В следствии этого, в государственном стандарте высшего профессионального образования выделяют три уровня:  федеральный, национально-региональный и вузовский. 
Федеральный уровень содержания образования определяет те нормативы, соблюдение которых обеспечивает единство высшего образования в России, а также интеграцию личности выпускника в систему мировой экономики и культуры. 
Национально-региональный уровень содержит нормативы в области родного языка и литературы, вопросы истории, искусства, региональной экономики и др. Они относятся к компетенции региональных органов управления образованием. 
Вузовский уровень содержания образования определяется самим образовательным учреждением. Но в стандарте указан объем содержания образования (в часах), отражающего специфику и направленность отдельного образовательного учреждения .

**Comment by kleidemos** [comment]
1. После списка должна следовать пустая строка, чтобы следующий абзац шел отдельно.
2. Выдели уровни в отдельный список. Их не видно пока не прочтешь.
