### ISSUE TITLE
7. Основные образовательные программы

### ISSUE THREAD

**Issue by AlmazAltynguzin** [kleidemos/PsychologyAndPedagogyCredit#33]
Действующая система подготовки специалистов дополнена двухуровневой структурой высшего образования. 

Образовательная программа первого уровня (бакалавриат) обеспечивает базовое высшее образование и охватывает все области науки, техники и культуры. Она предоставляет студентам возможность овладеть системой научных знаний о человеке и обществе, истории и культуре, получить фундаментальную естественнонаучную подготовку и основы профессиональных знаний по направлениям обучения (специальности). Срок обучения по программе базового высшего образования составляет четыре года на основе общего (полного) среднего образования. Лицам, получившим базовое высшее образование, выдается диплом с присвоением степени бакалавра и указанием специальности.

Образовательная программа второго уровня (магистратура) имеет целью подготовку специалистов, готовых к самостоятельной творческой профессиональной деятельности. Эта программа предполагает преимущественно исследовательский характер будущей профессиональной деятельности. Срок ее реализации два года, после чего выдается диплом о высшем образовании с присвоением степени магистра наук.

Образовательные программы в соответствии с внешними и внутренними целями подразделяются на общие для всех и индивидуальные для каждого студента. Между двумя видами программ существует динамическая связь и взаимодействие: общая программа деятельности предполагает разработку индивидуальных программ. По отношению к образовательным стандартам общая программа образования имеет федеральный, региональный и вузовский компоненты, а индивидуальная программа – вариативную часть образования, устанавливаемую на основе личного выбора студента.

**Comment by kleidemos** [comment]
Структурой выдели бакалавриат и магистратуру.
