### ISSUE TITLE
17. Основы лекционного преподавания

### ISSUE THREAD

**Issue by AlmazAltynguzin** [kleidemos/PsychologyAndPedagogyCredit#34]
Лекция как форма учебного процесса имеет ряд отличительных черт, в частности она:
- дает целостное и логичное освещение основных положений учебной дисциплины;
-вооружает студентов методологией изучения данной науки;
- оперативно знакомит студентов с последними данными наук;
- органично сочетает обучение с воспитанием;
- нацеливает студентов на самостоятельную работу и определяет основные ее направления.

Достоинства: экономичный способ обучения, передает основное содержание дисциплины.
Основные функции лекции: познавательная, развивающая, воспитательная, ориентирующая.
Каждая лекция в вузе должна:
- иметь четкую структуру и логику раскрытия последовательно излагаемых вопросов;
- иметь твердый теоретический и методический стержень;
- иметь законченный характер освещения определенной темы, тесную связь с предыдущим материалом;
- быть доказательной и аргументированной, иметь четко выраженную связь с практикой;
- находиться на современном уровне развития науки и техники, содержать прогноз их развития на ближайшие годы;
- отражать методическую обработку материала;
- быть наглядной, сочетаться, по возможности, с демонстрацией аудиовизуальных материалов, макетов, моделей и образцов;
- излагаться четким и ясным языком, содержать разъяснение всех вновь вводимых терминов и понятий;
- быть доступной для восприятия данной аудиторией.

Структура лекции:
1. Вступление. Определяется тема, план, цель лекции.
2. Изложение - – основная часть лекции, в которой реализуется научное содержание темы, ставятся все узловые вопросы, приводится вся система доказательств с использованием наиболее целесообразных методических приемов.
3. Заключение обобщает в кратких формулировках основные идеи лекции, логически завершая ее как целостное.

Виды лекции:
1) Вводная, включает:
- определение учебной дисциплины;
- краткую историческую справку о развитии этой отрасли знаний;
- цели и задачи учебной дисциплины;
- основные понятия соответствующей науки;
- распределение времени по видам учебных занятий и по семестрам;
- основную и дополнительную учебную и методическую литературу;
- особенности самостоятельной работы слушателей над учебной дисциплиной и формы участия в научно-исследовательской работе;
- отчетность по курсу.

2) Заключительная лекция предназначена для обобщения полученных значений и раскрытия перспектив дальнейшего развития данной науки. Содержит:
- общий обзор пройденного курса, основные выводы и обобщения;
- освещение современного состояния основных проблем данной области науки;
- трактовку главных линий дальнейшего развития науки, указание существующих проблем и намеченных путей их решения.

3) Установочная лекция читают слушателям заочного обучения на сборах как начало самостоятельного изучения определенного курса в период между сессиями.

_Особенности подготовки лекции._
Подготовка лекции – это процесс отбора и структурирования содержания учебного материала, распределение его по времени, продумывание логики построения лекции, выделение наиболее важных моментов из всего материала, который нужно изложить, выбор методов обучения.
Главнейшее требование при подготовке к лекции – поставить проблему и сделать это правильно.
Алгоритм подготовки:
1) Определить тему и цель лекции
2) Определение содержания обучения, т.е. - отбор учебного материала, его анализ и структурирование.
3) Построение методики изложения

_Особенности чтения лекции._
1) Начало: напоминание пройденного материала, объявления темы и постановки целей.
2) Изложение содержания. 
Проблемно построенная лекция  – это рассмотрение в поисковом плане одной или нескольких учебных проблем на основе анализирующего рассуждения, описания истории, открытий, разбора и анализа точек зрения и других способов движения к научной истине.
Актуализация знаний - воспроизведение материала. 
Постановка проблемы, решение которой должно обеспечить получение новых знаний.
Предварительный логический анализ учебного материала.
Выдвижение гипотез. Проверка гипотез.
3) Заключительная часть лекции имеет следующую структуру:
- лектор напоминает изученные вопросы;
- излагает опорные точки по каждому вопросу и делает по ним обобщения;
- подводит краткий итог по всей теме и отвечает на вопросы;
- выдает задание на дом.

**Comment by kleidemos** [comment]
Вот у вас сегодня гигантомания развилась. Зачем столько? Это явные перебор.

**Comment by kleidemos** [comment]
1. Список некошерный.
2. _Убери название билета из description._

**Comment by AlmazAltynguzin** [comment]
Я еще сократил это в полтора раза. Просто я боюсь что-то еще убирать. Вдруг препод решит прочитать и докопается, что вот этого нет

**Comment by kleidemos** [comment]
Ощущение, что ты все вписал.
