### ISSUE TITLE
27. Структура педагогической деятельности.

### ISSUE THREAD

**Issue by a-valitov** [kleidemos/PsychologyAndPedagogyCredit#35]
Педагогическая деятельность (как и любой вид деятельности) включает такие компоненты, как субъект, объект, цель, мотивы, средства, действия, способы действия и результат.

**Субъект** педагогической деятельности – это тот, кто планирует и организовывает образовательный процесс в вузе, т.е. каждый преподаватель и весь профессорско-преподавательский состав (педагогический коллектив) вуза.

**Объект** (предмет) педагогической деятельности – студент, его учебно-познавательная деятельность. Преподаватель призван управлять этой деятельностью, т.е. планировать, организовывать, контролировать, оценивать и стимулировать ее.

**Цели** педагогической деятельности заложены в образовательных стандартах специальностей, в учебных программах дисциплин и совпадают с целями образования. Но конкретные цели и задачи лекций, семинарских, практических и других видов занятий (какими знаниями или умениями должны овладеть студенты по результатам занятия) определяются самим преподавателем.

Основными **мотивами** педагогической деятельности преподавателя являются интерес к преподаваемой дисциплине (науке), стремление вовлечь в процесс познания студентов, понимание и переживание им большой значимости этой работы для общества, а также мотив власти.

К **средствам** педагогической деятельности относятся: живое слово (речь) преподавателя, учебная и научная литература, наглядные пособия, технические средства обучения, в том числе компьютер и электронные издания, лабораторное оборудование и т.д. К средствам труда преподавателя необходимо отнести также его знания, умения и способности (профессиональную компетентность).
 
**Действия** преподавателя как структурные единицы педагогической деятельности весьма многообразны. Они связаны с планированием, подготовкой и проведением занятий, контролем и оценкой знаний и умений студентов, с методической работой, общением со студентами, организацией самостоятельной работы студентов, с решением других задач.

**Способы действий** преподавателя (методы обучения и воспитания): объяснение, проблемное изложение, показ (иллюстрация), решение задач, беседа с учащимися, организация дискуссий, самостоятельной работы студентов и т.д.

**Результат** педагогической деятельности определяется тем, насколько достигнуты цели образования, т.е. уровнем знаний и умений студентов, их воспитанности. На выходе образовательного процесса – личность молодого специалиста, обладающего не только профессиональной компетентностью, но и научным мировоззрением, гуманитарными знаниями, системой нравственных, эстетических, коммуникативных качеств, высоким уровнем интеллекта и интеллигентности.

**Comment by kleidemos** [comment]
Чёт много, но для конспекта пойдет.
