### ISSUE TITLE
22. Игровые технологии обучения

### ISSUE THREAD

**Issue by MIrzhanov** [kleidemos/PsychologyAndPedagogyCredit#37]
Игра – один из основных видов деятельности человека. Детская игра заключается в подражании детьми действий взрослых. В ролевой игре участники берут на себя должностные, социальные роли и в игровой ситуации воссоздают деятельность и отношения людей. Учебная игра способствует усвоению конкретных знаний, умений и навыков.

Дидактический смысл учебной игры:
1. Изучение и усвоение учебного материала осуществляется путем игровой деятельности. 
1. Самостоятельные действия. В процессе игровой деятельности создаются условия для возникновения и разрешения проблемных ситуаций. Обучение становится личностно значимым для студентов.
1. Студент в ходе решения проблемных ситуаций игры становится самостоятельным.

Цель игрового обучения – научить студентов эффективно работать в коллективе (в группе). 
Примером являются деловые игры. Деловая игра заключается в имитации различных ситуациях на производстве путем совместной деятельности по заданным правилам. Деятельность в деловой игре сочетает в себе учебные и профессиональные элементы. Знания и умения усваиваются в процессе решения задач в игре.

Для достижения поставленных учебных целей в деловую игру следует заложить пять принципов:

1. принцип имитационного моделирования. Имитационная модель производства и игровая модель проф деятельности;
1. принцип проблемности содержания игры. Игра строится на основе системы проблемных задач;
1. принцип совместной деятельности. Имитация производственных функций путём взаимодействия студентов;
1. принцип диалогического общения. Участник в соответствии со своей ролью высказывает свою точку зрения, отвечает на вопросы, слушает других участников и т.д;
1. принцип двуплановости игровой деятельности. Достижение игровой и педагогической целей в процессе игры. Игровая цель – совместное решение поставленной проблемы путем игры. Педагогические цели: вовлечение студента мыслительную деятельность;  усвоение знаний, умений и навыков; развитие мышления в проф сфере в теории и на практике;

Игровые методы повышают мотивации учебной деятельности учащихся. В ходе совместной игры и решения проблем формируются определенные человеческие отношения между студентами, преподавателем.

**Comment by kleidemos** [comment]
Стоило бы чуть добавить типографики и выделить смысл в список.

**Comment by MIrzhanov** [comment]
сократил
