### ISSUE TITLE
23. Технологии дистанционного обучения

### ISSUE THREAD

**Issue by MIrzhanov** [kleidemos/PsychologyAndPedagogyCredit#38]
Дистанционное обучение – это обучение на расстоянии с помощью различных средств. Его отличительная особенность состоит в том, что обучающиеся могут сами получать требуемые знания, пользуясь современными информационными ресурсами. Информационные ресурсы (компьютерные, мультимедиа, обучающие системы, электронные библиотеки) вместе с традиционными инструментами обучения создают образовательную среду для широкой аудитории.

Основой дистанционного обучения является самостоятельная деятельность студента. При этом дистанционное обучение не исключает возможностей коммуникации с преподавателями или с другими партнерами.

Модель предварительного обучения студентов методике дистанционного обучения
включает три этапа. 
1) Формирование навыков для обучения в дистанционном режиме. Также обучающиеся должны приобрести навыки для эффективной работе с дистанционным курсом.
2) Интенсивное обучение по дистанционным курсам. Формирование необходимых умений и навыков участия в конференциях.
3) Формирование умений осуществлять поиск образовательных ресурсов в сети, соизмерять свои знания умения и навыки с требованиями курса, использовать разнообразные интерактивные возможности в выбранном курсе.

**Comment by MIrzhanov** [comment]
Дистанционное обучение – это обучение на расстоянии с помощью учебников, учебно-программных, компьютерных, телекоммуникационных и других средств. Его отличительная особенность состоит в том, что обучающиеся могут сами получать требуемые знания, пользуясь развитыми информационными ресурсами, предоставляемыми современными информационными технологиями. Информационные ресурсы, такие как базы данных и знаний, компьютерные, в том числе мультимедиа, обучающие и контролирующие системы, видео- и аудиозаписи, электронные библиотеки, вместе с традиционными учебниками и методическими пособиями создают уникальную образовательную среду, доступную широкой аудитории.

В центре процесса дистанционного обучения находится не преподавание, а самостоятельная деятельность студента по овладению знаниями, умениями и навыками.
При этом обучающийся должен владеть не только познавательными навыками работы с компьютером, но и способами работы с учебной и научной информацией, с которой он встречается в различных интернет-ресурсах. Речь идет о том, что сотрудники должны хорошо владеть различными видами чтения – изучающим, поисковым, ознакомительным, работать с электронными справочниками и словарями.

Дистанционное обучение, индивидуальное по своей сути, не исключает возможностей коммуникации не только с преподавателями, но и с другими партнерами, а также сотрудничества в процессе разного рода познавательной и творческой деятельности.

Дистанционное образование имеет ряд преимуществ перед традиционной системой очного и заочного образования, а именно:
• преодолеваются пространственные и временные барьеры в получении научной, учебной, справочной или иной информации;
• увеличивается число потенциальных участников образовательного процесса – студентов, преподавателей, специалистов-практиков, ученых, которые оперативно взаимодействуют друг с другом с помощью компьютерных сетей, в том числе Интернета;
• обеспечивается широкий доступ к лучшим мировым образовательным ресурсам;
• существенно увеличиваются возможности учебного заведения за счет формирования образовательной информационной среды, в которой обучаемый самостоятельно или под руководством преподавателя может изучать интересующий материал;
• появляется возможность формировать уникальные образовательные программы за счет комбинирования курсов, предоставляемых образовательными учреждениями, в том числе различных стран;
• обучение становится более мотивированным, технологичным и индивидуализированным;
• появляется возможность опубликовать студенческие работы в Интернете;
• студенты и преподаватели имеют возможность распределять время занятий по удобному для себя графику и темпу, выбирать и использовать для занятий разнообразные технические средства,
наглядные пособия, программы обучения и т.д.
• дистанционное обучение имеет большое социальное значение, так как позволяет удовлетворять в полной мере образовательные потребности населения; оно снижает стоимость обучения

Модель предварительного обучения студентов методике дистанционного обучения
включает три этапа. 
На первом этапе формируются первоначальные знания, умения и навыки, необходимые для обучения в дистанционном режиме. В результате обучения на первом этапе обучающиеся
должны познакомиться с такими понятиями, как компьютерная сеть Интернет, гипертекст, гиперссылка, веб-документ, браузер, электронная почта и др. Кроме того, обучающиеся должны приобрести устойчивые умения и навыки, обеспечивающие эффективную работу с дистанционным курсом, в том числе умение загрузить дистанционный обучающий курс по указанному адресу, использовать навигационные возможности при освоении материала курса, умение реализовывать интерактивный диалог при выполнении задания и т.п.

Второй этап характеризуется формированием основных знаний, умений и навыков, необходимых для обучения в дистанционном режиме. На данном этапе осуществляется интенсивное обучение по дистанционным курсам. Обучение в рамках этого этапа должно обеспечить формирование необходимых умений и навыков эффективного участия в тематических телесеминарах и конференциях. Сюда относятся: умение задавать вопросы по теме дискуссии, отвечать на вопросы, аргументировать свое мнение, умение выделять главную мысль и т.д.

На третьем этапе формируются соответствующие навыки самостоятельной работы в дистанционном режиме. В результате обучения у студентов на достаточно высоком уровне должны быть сформированы умения осуществлять поиск образовательных ресурсов в Интернете
и в локальной сети, соизмерять свои знания умения и навыки с требованиями дистанционного курса, использовать разнообразные интерактивные возможности в выбранном дистанционном курсе.

Для ускорения этого процесса внедрения дистанционного образования должны быть решены такие проблемы, как:
• разработка педагогически обоснованной концепции дистанционного образования и нормативно-правовой базы ее реализации;
• развитие и адаптация корпоративных сетей учебных заведений, доведение пропускной способности телекоммуникационных каналов до минимально необходимой;
• поиск, приобретение и внедрение существующих разработок электронных учебников и учебно-методических материалов;
• организация подготовки и повышения квалификации преподавателей и технологического персонала в области технологии дистанционного обучения;
• создание электронной библиотеки, включение ее в корпоративную сеть библиотек региона, обеспечение доступа к открытым библиотекам в Интернете;
• вступление учебного заведения в Ассоциацию открытых университетов России, международные ассоциации электронных библиотек;
• проведение систематических научно-педагогических исследований с целью изучения эффективности и дальнейшей модернизации технологии дистанционного обучения на всех уровнях образовательного процесса.

**Comment by kleidemos** [comment]
Перенес в description.

**Comment by kleidemos** [comment]
При переформулировке можно сократить раза в три. В конспекты пойдет, но потом высушу, если будет время.
