### ISSUE TITLE
24. Особенности развития личности студента

### ISSUE THREAD

**Issue by MIrzhanov** [kleidemos/PsychologyAndPedagogyCredit#39]
В студенческом возрасте происходит  психическое развитие человека, меняется вся структура личности в связи с вхождением в новые социальные общности. В связи с этим существуют психические особенности студенческого возраста.

Время учебы в вузе является периодом интенсивной социализации студента, становления личности в целом. Характерными чертами возрастной группы (17–23 года) являются активное стремление к самопознанию, самоопределению и самоутверждению. Однако юношеству присуща и определенная неустойчивость (в силу отсутствия достаточного жизненного опыта и т.д.).

Развитие студента на различных курсах имеет некоторые особые черты.

1) Приобщение абитуриента к студенческим формам коллективной жизни. 
2) Получение общей подготовки, формирование культурных запросов и потребностей.
3) Начало специализации, укрепление интереса к научной работе. 
4) Знакомство со специальностью в период прохождения учебной практики. 
5) Скорое окончание вуза, формирование четких практических установок на будущий род деятельности. 

Личность студента  развивается в ряде направлений, а именно:
- укрепляется профессиональная направленность;
- «профессионализируются» психические процессы, состояния, опыт;
- повышаются чувство долга, ответственность за успех профессиональной деятельности, проявляется индивидуальность;
- растут притязания в области своей будущей профессии;
- растут общая зрелость и устойчивость личности студента;
- повышается удельный вес самовоспитания студента в формировании качеств, опыта, необходимых ему как будущему специалисту;
- крепнет профессиональная самостоятельность.

**Comment by MIrzhanov** [comment]
В студенческом возрасте происходит дальнейшее психическое развитие человека, сложное переструктурирование психических функций интеллекта, меняется вся структура личности в связи
с вхождением в новые, более широкие и разнообразные социальные общности. Изучение закономерностей развития человека в студенческом возрасте как в периоде интенсивного интеллектуального развития, формирования учебно-профессиональной деятельности, усвоения
роли студента, вхождения в новую, «взрослую» жизнь позволяет говорить о психических особенностях студенческого возраста.

Студент - учащийся высшего, а в некоторых странах и среднего учебного заведения. 
Студенчество – учащиеся высших и средних профессиональных учебных заведений. Термин «студенчество» обозначает собственно студентов как социально-демографическую группу, характеризующуюся определенной численностью, половозрастной структурой, территориальным расслоением и т.д., а также определенное общественное положение, роль и статус; особую фазу, стадию социализации (студенческие годы), которую проходит значительная часть молодежи и которая отличается определенными социально-психологическими особенностями.

Несмотря на различия своего социального происхождения и, следовательно, материальных возможностей, студенчество связано общим видом деятельности и образует в этом смысле определенную социально-профессиональную группу. Общая деятельность в сочетании с территориальным сосредоточением порождает у студенчества известную общность интересов, групповое самосознание, специфическую субкультуру и образ жизни, причем это дополняется
и усиливается возрастной однородностью, которую не имеют другие социально-профессиональные группы. Социально-психологическая общность объективируется и закрепляется деятельностью целого ряда экономических, культурно-просветительских, спортивных и бытовых студенческих организаций.

В плане общепсихического развития время учебы в вузе является периодом интенсивной социализации студента, развития высших психических функций, становления всей интеллекту-
альной системы и личности в целом. Если рассматривать студенчество, учитывая лишь биологический возраст, то его следует отнести к периоду юности как переходному этапу развития человека между детством и взрослостью. Поэтому в зарубежной психологии этот период связывают с процессом взросления.

Характерными чертами возрастной группы (17–23 года) являются активное отношение к действительности, стремление к самопознанию, самоопределению и самоутверждению в качестве субъекта социальной жизни. Вместе с тем стремлению юношества к активному самоопределению присуща и определенная неустойчивость, которая проявляется в импульсивности и разбросанности, иллюзорном и экзотическом романтизме, разочаровании и пессимизме, скептицизме и нигилизме, негативном максимализме и волевой дисгармонии.

Развитие студента на различных курсах имеет некоторые особые черты.

Первый курс – решается задача приобщения недавнего абитуриента к студенческим формам коллективной жизни. 

Второй курс – это период самой напряженной учебной деятельности студентов. Студенты получают общую подготовку, формируются их широкие культурные запросы и потребности. Процесс адаптации к данной среде в основном завершен.

Третий курс – начало специализации, укрепление интереса к научной работе. Настоятельная необходимость в специализации зачастую приводит к сужению сферы разносторонних интересов личности. 

Четвертый курс – первое реальное знакомство со специальностью в период прохождения учебной практики. Для поведения студентов характерен интенсивный поиск более рациональных путей и форм специальной подготовки, происходит переоценка студентами многих ценностей жизни и культуры.

Пятый курс – в перспективе скорое окончание вуза, формируются четкие практические установки на будущий род деятельности. Студенты постепенно отходят от коллективных форм
жизни вуза.

Поиски друга жизни играют на третьем–четвертом курсах большую роль, оказывая влияние и на успеваемость, и на общественную деятельность студентов. Интерес к противоположному полу занимает значительное место в мыслях и поведении студентов. Но было бы ошибкой видеть в этом негативное явление. Интимные отношения нередко способствуют повышению желания лучше учиться, рабочему настроению, творческой активности. Вступление в брак многих студентов к концу учебы не ведет к распаду студенческих коллективов, хотя число непосредственных межличностных и межгрупповых контактов среди его членов несколько уменьшается.

Изучение личности студента в практике высшей школы осуществляется по следующим показателям: мотивы поступления в вуз, уровень общеобразовательной подготовки, характер деятельности до поступления в вуз, степень сформированности умений и навыков самостоятельной работы, характер интересов, увлечений, уровень развития способностей, особенности характера, состояние здоровья, соответствие их содержанию и требованиям к будущей профессии.

Для выявления всего этого широко используются опросы, наблюдения, рецензирование самостоятельных работ студентов, результаты выполнения контрольных заданий, зачетов, экзаменов, тестирование. На основе такого изучения осуществляется дифференцированный подход к студентам. Выявляются трудности в учебе и практической работе, определяются предпочитаемые учебные дисциплины и виды занятий, самооценка уровня своей деятельности и себя как личности, степень удовлетворенности.

В целом же личность студента как будущего специалиста с высшим образованием развивается в ряде направлений, а именно:
• укрепляется профессиональная направленность, вырабатываются необходимые способности;
• совершенствуются, «профессионализируются» психические процессы, состояния, опыт;
• повышаются чувство долга, ответственность за успех профессиональной деятельности, рельефнее выступает индивидуальность студента;
• растут притязания в области своей будущей профессии;
• на основе интенсивной передачи социального и профессионального опыта и формирования нужных качеств растут общая зрелость и устойчивость личности студента;
• повышается удельный вес самовоспитания студента в формировании качеств, опыта, необходимых ему как будущему специалисту;
• крепнут профессиональная самостоятельность и готовность к будущей практической работе.

**Comment by kleidemos** [comment]
Перенес в description.

**Comment by MIrzhanov** [comment]
В студенческом возрасте происходит дальнейшее психическое развитие человека, меняется вся структура личности в связи с вхождением в новые социальные общности. Изучение закономерностей развития человека в студенческом возрасте позволяет говорить о психических особенностях студенческого возраста.

Несмотря на различия своего социального происхождения и, следовательно, материальных возможностей, студенчество связано общим видом деятельности и образует в этом смысле определенную социально-профессиональную группу. 

В плане общепсихического развития время учебы в вузе является периодом интенсивной социализации студента, развития высших психических функций, становления всей интеллекту-
альной системы и личности в целом. Характерными чертами возрастной группы (17–23 года) являются активное отношение к действительности, стремление к самопознанию, самоопределению и самоутверждению в качестве субъекта социальной жизни. Вместе с тем стремлению юношества к активному самоопределению присуща и определенная неустойчивость.

Развитие студента на различных курсах имеет некоторые особые черты.

1) Решается задача приобщения недавнего абитуриента к студенческим формам коллективной жизни. 
2) Получение общей подготовки, формирование культурных запросов и потребностей. Процесс адаптации к данной среде в основном завершен.
3) Начало специализации, укрепление интереса к научной работе. Происходит сужение сферы разносторонних интересов личности. 
4) Знакомство со специальностью в период прохождения учебной практики. Для поведения студентов характерен интенсивный поиск более рациональных путей и форм специальной подготовки, происходит переоценка студентами многих ценностей жизни и культуры.
5) Скорое окончание вуза, формирование четких практических установок на будущий род деятельности. Студенты постепенно отходят от коллективных форм жизни вуза.

Личность студента  развивается в ряде направлений, а именно:
- укрепляется профессиональная направленность, вырабатываются необходимые способности;
- совершенствуются, «профессионализируются» психические процессы, состояния, опыт;
- повышаются чувство долга, ответственность за успех профессиональной деятельности, рельефнее выступает индивидуальность студента;
- растут притязания в области своей будущей профессии;
- на основе интенсивной передачи социального и профессионального опыта и формирования нужных качеств растут общая зрелость и устойчивость личности студента;
- повышается удельный вес самовоспитания студента в формировании качеств, опыта, необходимых ему как будущему специалисту;
- крепнут профессиональная самостоятельность и готовность к будущей практической работе.
